{% set data = load_setup_py_data() %}

package:
  name: pytask
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff. However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  noarch: python
  number: 0
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - attrs >=17.4.0
    - click
    - click-default-group
    - networkx
    - pluggy
    - pony >=0.7.13

  run:
    - python >=3.6
    - attrs >=17.4.0
    - click
    - click-default-group
    - networkx
    - pluggy
    - pony >=0.7.13

test:
  imports:
    - pytask
  requires:
    - pexpect
    - pytest
  source_files:
    - tox.ini
    - src
    - tests
  commands:
    - pytask --help
    - pytask --version
    - pytask clean
    - pytask markers
    - pytask collect

    - pytest tests

about:
  home: https://github.com/pytask-dev/pytask
  license: none
  summary: In its highest aspirations, pytask tries to be pytest as a build system.
  doc_url: https://pytask-dev.readthedocs.io/en/latest
  dev_url: https://github.com/pytask-dev/pytask/
