name: zizmor

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: Scan GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: '3.13'

      - name: Run zizmor
        run: uvx --from zizmor zizmor --format=github .

      - name: Generate SARIF report
        if: always()
        run: uvx --from zizmor zizmor --format=sarif --no-exit-codes . > zizmor.sarif

      - name: Upload SARIF report
        if: >
          always() &&
          (github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository)
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
        with:
          sarif_file: zizmor.sarif
